### PR TITLE
[#103] Fix paging number increasing when api call fails and clearing …

### LINKED ISSUE #103: Fix: Pagination keep increasing when api call is failed and showing blank screen when pull to refresh without internet
## Issue

On Home Screen, when api call is failed, pagination is still increasing and thus api call doesn't call anymore when connection is restored. Also when pull to refresh and api call failed, the cache is cleared before the api call is a success.

## Expected

- Do not increase the page number when api call is failed
- Do not clear the cache when api call is failed

## Steps to reproduce

1. Go to the home screen
2. Disconnect the internet 
3. Swipe left until the next page is called
5. Pull to refresh

### PR DESCRIPTION
**Pull request by kaungkhantsoe**
Closes #103 

## What happened 👀

On Home Screen, when api call is failed, pagination is still increasing and thus api call doesn't call anymore when connection is restored. Also when pull to refresh and api call failed, the cache is cleared before the api call is a success.

## Insight 📝

- Refactor fetching logic to be based on the total number of records instead of hard code `pageNumber`
- Fix some test classes

## Proof Of Work 📹

https://user-images.githubusercontent.com/32578035/191726479-87bfcb04-d6c1-431c-b714-58ea410e6528.mp4

### CODE REVIEW

File: app/src/main/java/com/kks/nimblesurveyjetpackcompose/model/response/MetaResponse.kt [hunk 1]
```diff
@@ -16,3 +17,11 @@ data class MetaResponse(
...
     val message: String?
 )
+
+fun MetaResponse.toMeta() = Meta(
+    page = page ?: 0,
+    pages = pages ?: 0,
+    pageSize = pageSize ?: 0,
+    records = records ?: 0,
+    message = message.orEmpty()
+)
```
Comment (ryan-conway) [inline app/src/main/java/com/kks/nimblesurveyjetpackcompose/model/response/MetaResponse.kt]: If we always want a default value of `Meta`, we can update this to
```suggestion
fun MetaResponse?.toMeta() = Meta(
    page = this?.page ?: 0,
    pages = this?.pages ?: 0,
    pageSize = this?.pageSize ?: 0,
    records = this?.records ?: 0,
    message = this?.message.orEmpty()
)
```

File: app/src/main/java/com/kks/nimblesurveyjetpackcompose/repo/home/HomeRepoImpl.kt [hunk 2]
```diff
@@ -26,17 +27,17 @@ class HomeRepoImpl @Inject constructor(
...
         val apiResult = safeApiCall(Dispatchers.IO) { apiInterface.getSurveyList(pageNumber, pageSize) }
         when (apiResult) {
             is ResourceState.Success -> {
                 apiResult.data.data?.let { surveyResponseList ->
+                    if (isClearCache) surveyDao.clearSurveys()
                     surveyDao.addSurveys(surveyResponseList.map { it.toSurvey() })
-                    getNumberOfPage(apiResult.data.meta?.pages ?: 0)
                 }
-                emit(ResourceState.Success(Unit))
+                emit(ResourceState.Success(apiResult.data.meta?.toMeta() ?: Meta()))
```
Comment (ryan-conway) [inline app/src/main/java/com/kks/nimblesurveyjetpackcompose/repo/home/HomeRepoImpl.kt]: and then this will become 
```suggestion
                emit(ResourceState.Success(apiResult.data.meta.toMeta()))
```
What do you think? 😄

File: app/src/main/java/com/kks/nimblesurveyjetpackcompose/viewmodel/home/HomeViewModel.kt [hunk 3]
```diff
@@ -105,20 +100,23 @@ class HomeViewModel @Inject constructor(
         }
     }
 
-    private fun getSurveyList() {
-        if (_currentPageNumber.value <= totalNumberOfPage) {
+    private fun getSurveyList(isClearCache: Boolean = false) {
+        val pageNumber = ((if (isClearCache) START_SURVEY_NUMBER else _surveyList.value.size) / DEFAULT_PAGE_SIZE) + 1
+        if ((pageNumber <= _pages && _surveyList.value.size < _records) || isClearCache) {
```
Comment (ryan-conway) [inline app/src/main/java/com/kks/nimblesurveyjetpackcompose/viewmodel/home/HomeViewModel.kt]: `_pages` doesn't seem too clear in terms of intent 🤔 How about `_pageCount` or `_pageTotal` or `_numberOfPages` instead? 🤔 
Same with `pageNumber`, tho lower priority 🤣 How about `currentPage`? 🤔

**Review by ryan-conway — COMMENTED** [review]
The rest LGTM 👍🏻

**Review by ryan-conway — APPROVED** [review]
👌🏻

**Review by AVI5HEK — APPROVED** [review]
LGTM 🚀
