### PR TITLE
[#94] Fix IncludedResponse declared alerts as wrong type

### LINKED ISSUE #94: Fix: Wrong object type receiving for alerts in survey detail
## Issue

Error while fetching survey detail when there are `alerts` included in the response. 

## Expected

```
 "alerts": [
                    {
                        "id": "683bf1be2bd1703c7915",
                        "alert_type": "email",
                        "recipient": "chsuphawadee@tops.co.th",
                        "is_only_business_hours": true,
                        "answer_id": "d781429576834e54a3ce"
                    },
                    {
                        "id": "c043d0a9070952bf0c32",
                        "alert_type": "email",
                        "recipient": "Chwilaiwan@tops.co.th",
                        "is_only_business_hours": true,
                        "answer_id": "d781429576834e54a3ce"
                    },
                    {
                        "id": "3933b5cfc146c7981dd0",
                        "alert_type": "email",
                        "recipient": "cusserv@tops.co.th",
                        "is_only_business_hours": true,
                        "answer_id": "d781429576834e54a3ce"
                    }
]
```

## Steps to reproduce

1. Go to the application
2. Scroll to the 13th survey and click detail button

### PR DESCRIPTION
**Pull request by kaungkhantsoe**
closes #94 

## What happened 👀

`alerts` in `IncludedResponse` is declared with wrong type and having deserializing error when `alerts` is not null.

## Insight 📝

Refactor `alerts` from `List<String>` type to `List<AlertResponse>` type with the following response:
```
 "alerts": [
                    {
                        "id": "683bf1be2bd1703c7915",
                        "alert_type": "email",
                        "recipient": "chsuphawadee@tops.co.th",
                        "is_only_business_hours": true,
                        "answer_id": "d781429576834e54a3ce"
                    },
                    {
                        "id": "c043d0a9070952bf0c32",
                        "alert_type": "email",
                        "recipient": "Chwilaiwan@tops.co.th",
                        "is_only_business_hours": true,
                        "answer_id": "d781429576834e54a3ce"
                    },
                    {
                        "id": "3933b5cfc146c7981dd0",
                        "alert_type": "email",
                        "recipient": "cusserv@tops.co.th",
                        "is_only_business_hours": true,
                        "answer_id": "d781429576834e54a3ce"
                    }
                ]
```

## Proof Of Work 📹

https://user-images.githubusercontent.com/32578035/190597475-32a9e5ba-ac98-48dd-b207-188ca1bfd7a1.mp4

### CODE REVIEW

File: app/src/main/java/com/kks/nimblesurveyjetpackcompose/model/response/IncludedResponse.kt [hunk 1]
```diff
@@ -79,8 +79,17 @@ data class IncludedAnswerResponse(
...
-    )
+        @Json(name = "alerts") var alerts: List<AlertResponse> = emptyList()
+    ) {
+        @JsonClass(generateAdapter = true)
+        data class AlertResponse(
+            @Json(name = "id") var id: String? = null,
+            @Json(name = "alert_type") var alertType: String? = null,
+            @Json(name = "recipient") var recipient: String? = null,
+            @Json(name = "is_only_business_hours") var isOnlyBusinessHours: Boolean? = null,
+            @Json(name = "answer_id") var answerId: String? = null
```
Comment (ryan-conway) [inline app/src/main/java/com/kks/nimblesurveyjetpackcompose/model/response/IncludedResponse.kt]: Question, why don't we use `val` instead of `var`? Isn't it preferred to have data classes be immutable?

Comment (kaungkhantsoe) [reply app/src/main/java/com/kks/nimblesurveyjetpackcompose/model/response/IncludedResponse.kt]: Ahh yes, my bad.

**Review by ryan-conway — APPROVED** [review]
LGTM 👍🏻 

Shall we have another ticket to convert all data classes to use `val` too? What do you think? 😄

**Review by AVI5HEK — APPROVED** [review]
LGTM 🚀
